CREATE TABLE PRODUTO(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255),
);

CREATE TABLE FILIAL(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESCRICAO VARCHAR(255),
);

CREATE TABLE PEDIDO_ESTOQUE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    QTD_TOTAL INT NOT NULL ,
    VALOR_TOTAL DOUBLE NOT NULL ,
    TIPO_PEDIDO INT NOT NULL
);

CREATE TABLE ITEM_PEDIDO
(
    ID              INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_PEDIDO_ESTOQUE INT,
    ID_PRODUTO      INT,
    QTD_ITEM_PEDIDO INT,
    CONSTRAINT FK_ITP_REFERENCE_PRD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO (ID) ON DELETE CASCADE ON UPDATE CASCADE ,
    CONSTRAINT FK_ITP_REFERENCE_PED FOREIGN KEY (ID_PEDIDO_ESTOQUE) REFERENCES PEDIDO_ESTOQUE(ID) ON DELETE CASCADE ON  UPDATE CASCADE ,
);

CREATE TABLE ESTOQUE(
    ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_FILIAL INT,
    ID_PRODUTO INT,
    QTD_ESTOQUE INT,
    CONSTRAINT FK_EST_REFERENCE_FIL FOREIGN KEY (ID_FILIAL) REFERENCES FILIAL(ID) ON DELETE CASCADE ON UPDATE CASCADE ,
    CONSTRAINT FK_EST_REFERENCE_PRD FOREIGN KEY (ID_PRODUTO) REFERENCES PRODUTO(ID) ON DELETE CASCADE ON UPDATE CASCADE
)