INSERT INTO PRODUTO (DESCRICAO) VALUES ('ARROZ');
INSERT INTO PRODUTO (DESCRICAO) VALUES ('FEIJÃO');

INSERT INTO FILIAL (DESCRICAO) VALUES ('MIX COHAMA');
INSERT INTO FILIAL (DESCRICAO) VALUES ('MIX SÃO CRISTOVÃO');

INSERT INTO ESTOQUE (ID_FILIAL, ID_PRODUTO, QTD_ESTOQUE) VALUES ( 1,1,5 );
INSERT INTO ESTOQUE (ID_FILIAL, ID_PRODUTO, QTD_ESTOQUE) VALUES ( 2,2,4 );